application: mffmenzy
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css/jquery\.css
  static_files: css/jquery.css
  upload: css/jquery\.css
  
- url: /css/images/icons-18-white\.png
  static_files: css/images/icons-18-white.png
  upload: css/images/icons-18-white\.png
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest